B03.EE.BlanckeK.Web/Models/QuizViewModel.cs
using B03.EE.BlanckeK.Lib.Models;

namespace B03.EE.BlanckeK.Web.Models
{
    public class QuizViewModel
    {
        public Quiz Quiz { get; set; }
        public bool IsCorrect { get; set; }
    }
}

B03.EE.BlanckeK.Web/Controllers/QuizController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using B03.EE.BlanckeK.Lib.DTO;
using B03.EE.BlanckeK.Lib.Helpers;
using B03.EE.BlanckeK.Lib.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace B03.EE.BlanckeK.Web.Controllers
{
    public class QuizController : Controller
    {
        #region variables
        private readonly UserManager<IdentityUser> _userManager;
        private const string BaseUri = "http://localhost:61716/api/quiz";
        #endregion

        #region Constructor
        public QuizController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }
        #endregion


        public IActionResult Index()
        {
            ViewBag.UserId = _userManager.GetUserId(HttpContext.User);
            string quizUri = $"{BaseUri}/basic";
            List<QuizBasic> quizBasic = ApiConverter.GetApiResult<List<QuizBasic>>(quizUri);
            return quizBasic == null ? View("Error") : View(quizBasic);
        }

        #region Play Button
        public IActionResult PlayQuiz(string id)
        {
            string quizDetailUri = $"{BaseUri}/{id}";
            Quiz quizDetail = ApiConverter.GetApiResult<Quiz>(quizDetailUri);
            return quizDetail == null ? View("Error") : View(quizDetail);
        }
        #endregion

        public IActionResult CreateQuiz()
        {
            ViewBag.UserId = _userManager.GetUserId(HttpContext.User);
            ViewBag.Mode = "Create";
            return View("EditQuiz", null);
        }

        public IActionResult EditQuiz(string id)
        {
            ViewBag.UserId = _userManager.GetUserId(HttpContext.User);
            ViewBag.Mode = "Edit";
            string quizDetailUri = $"{BaseUri}/{id}";
            Quiz quizDetail = ApiConverter.GetApiResult<Quiz>(quizDetailUri);
            return quizDetail == null ? View("Error") : View("EditQuiz",quizDetail);
        }

        public async Task<IActionResult> DeleteQuiz(string id)
        {
            await ApiConverter.DelCallApi<Quiz>($"{BaseUri}/{id}");
            return RedirectToAction("Index");
        }
    }
}

B03.EE.BlanckeK.Web/Views/Quiz/EditQuiz.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@using B03.EE.BlanckeK.Lib.Models
@model Quiz

<script src="~/lib/vuejs/vue.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>


<article id="app" class="card">

    <header class="card-header text-center">{{ message }}{{ currentQuiz.quizName }} </header>
    <br />
    <!-- QuizName-->
    <div class="card-title" style="margin-bottom: 0">
        <div class="form-group card-header" style="background-color: aliceblue">
            <label class="col-md-12 text-center">QuizName</label>
            <input type="text" class="form-control col-md-12" v-model="currentQuiz.quizName">
        </div>
    </div>


    <div class="card-title" style="background-color: aliceblue; padding-top: 2%">
        <div class="text-center col-md-12">
            <p class="text-center col-md-12" style="color: chocolate; font-weight: bold; font-size: large">Questions</p>

            <div class="col-md-12 card-title text-center" v-for="question in currentQuiz.questions" :key="question.id">
                <!-- Question + answer div -->
                <div>

                    <!-- Question div -->
                    <div style="background-color: aliceblue" class="questionDiv form-group">
                        <a v-on:click="RemoveQuestion(question)" style="color: white;" class="badge btn btn-danger float-right">remove question</a>
                        <input type="text" class="form-control" id="question" v-model="question.questionText" />
                        <input name="questionId" type="hidden" class="form-control" id="questionId" v-model="question.id" />
                    </div>
                    <!-- Answer div -->
                    <div style="background-color: lightblue">
                        <label class="col-md-12" style="color: chocolate; font-weight: bold; font-size: large">{{ question.questionText }} </label>
                        <div class="col-md-12" v-for="answer in question.answerList" :key="answer.id">
                            <a v-on:click="RemoveAnswer(question, answer)" style="color: white;" class="badge btn btn-dark float-right">remove answer</a>
                            <input type="text" class="form-control" v-model="answer.answerText">
                            <label>
                                <input type="checkbox" v-model="answer.isCorrectAnswer" />
                                This answer is correct
                            </label>
                        </div>
                    </div>
                    <a v-on:click="AddNewAnswer(question)" style="color: white" class="badge btn btn-secondary col-md-12">Add answer for question: {{ question.questionText }} </a>
                </div>
                <hr style="background-color: chocolate" />
            </div>
            <a v-on:click="AddNewQuestion" style="color: white" class="badge btn btn-primary col-md-12">Add question</a>
        </div>
    </div>

    <div class="card-footer">
        <button v-on:click="SaveCompleteQuiz" class="btn btn-success">Save</button>
        <input type="button" onclick="location.href='../../quiz/index'" id="btnBackToList" class="btn btn-primary" value="Back to list"/>
    </div>
</article>

<script>

    var LoggedInUserid = "@SignInManager.UserManager.GetUserId(User)";

    var app = new Vue({
        el: '#app',
        data: {
            message: null,
            currentQuizId: null,
            currentQuiz: [],
            userid: LoggedInUserid,
            isEdit: false,
            apiUrl: "http://localhost:61716/api"
        },
        created: function() {
            var self = this;
            if ("@Model" === "") {
                self.isEdit = false;
                self.message = 'Creating Quiz: ';
                self.currentQuiz = {
                    "quizName": "",
                    "applicationUserId": self.userid,
                    "questions": [
                        {
                            "questionText": "",
                            "answerList": [
                                {
                                    "answerText": "",
                                    "isCorrectAnswer": false
                                }
                            ]
                        }
                    ]
                }
            } else {
                self.isEdit = true;
                self.message = 'Editing Quiz: ';
                self.currentQuizId = "@Model?.Id";
                self.fetchQuizDetails();
            }
        },
        methods: {
            AddNewQuestion: function () {
                var self = this;
                const newQuestion = {
                    "questionText": "",
                    "answerList":
                    [
                        {
                            "answerText": "",
                            "isCorrectAnswer": false
                        }
                    ]
                };
                self.currentQuiz.questions.push(newQuestion);
            },
            AddNewAnswer: function(question) {
                const newAnswer = {
                    "answerText": "",
                    "isCorrectAnswer": false
                }
                question.answerList.push(newAnswer);
            },
            RemoveQuestion: function (questionToRemove) {
                var self = this;
                self.currentQuiz.questions.splice($.inArray(questionToRemove, self.currentQuiz.questions), 1);
            },
            RemoveAnswer: function (selectedQuestion, answerToRemove) {
                selectedQuestion.answerList.splice($.inArray(answerToRemove, selectedQuestion.answerList), 1);
            },
            SaveCompleteQuiz: function () {
                var self = this;
                var ajaxConfig;
                var ajaxHeaders = new Headers();
                ajaxHeaders.append("Content-Type", "application/json");
                if (self.isEdit === true) {
                    ajaxConfig =
                    {
                        method: 'PUT',
                        body: JSON.stringify(this.currentQuiz),
                        headers: ajaxHeaders
                    };
                    let myRequest = new Request(`${self.apiUrl}/Quiz/${self.currentQuizId}`, ajaxConfig);
                    fetch(myRequest)
                        .then(res => res.json())
                        .then(console.log("geslaagd"));
                } else {
                    ajaxConfig =
                    {
                        method: 'POST',
                        body: JSON.stringify(self.currentQuiz),
                        headers: ajaxHeaders
                    };
                    let myRequest = new Request(`${self.apiUrl}/Quiz`, ajaxConfig);
                    fetch(myRequest)
                        .then(res => res.json());
                }
                redirectToOverView();

            },
            fetchQuizDetails: function() {
                var self = this;
                fetch(`${self.apiUrl}/Quiz/${self.currentQuizId}`)
                    .then(res => res.json())
                    .then(function(res) {
                        self.currentQuiz = res;
                        self.currentQuiz.questions = [];
                    })
                    .catch(err => console.error('Fout: FecthQuizDetails ' + err))
                    .then(function() {
                        self.fetchQuestionsForQuiz(self.currentQuiz);
                    });
            },
            fetchQuestionsForQuiz: function() {
                var self = this;
                fetch(`${self.apiUrl}/questions/quiz/${self.currentQuizId}`)
                    .then(res => res.json())
                    .then(function(res) {
                        self.currentQuiz.questions = res;
                        $.each(res,
                            function(i, currentQuestion) {
                                self.fetchAnswersForQuestion(currentQuestion.id, currentQuestion);
                            }
                        );
                    });

            },
            fetchAnswersForQuestion: function (questionId, currentQuestion) {
                var self = this;
                fetch(`${self.apiUrl}/answers/question/${questionId}`)
                    .then(res => res.json())
                    .then(function(res) {
                        currentQuestion.answerList = res;
                    });
            },
            redirectToOverView: function () {

                document.getElementById("#btnBackToList").click();

            }
        }
    });
</script>

B03.EE.BlanckeK.Web/Views/Quiz/Index.cshtml
@using B03.EE.BlanckeK.Lib.DTO

@model List<QuizBasic>


<h3 class="text-center">Overview quizzes</h3>
<div class="col-md-12">

    <ul class="card-columns list-group">
        <li class="btn-success text-right list-unstyled">
            @{
                if (ViewBag.Userid != null)
                {
                    <a asp-controller="Quiz" asp-action="CreateQuiz" class="col-md-12 float-right btn btn-success" style="color: white">Create New Quiz</a>
                }
                else
                {
                    <a asp-area="Identity"asp-page="/Account/Login" class="col-md-12 float-right btn btn-success" style="color: white">Login or Register to create you own quiz !!</a>
                }
            }


        </li>
        @foreach (QuizBasic quizBasic in Model)
        {
            <li class="list-group-item">
                <span><a class="btn btn-success" asp-controller="Quiz" asp-action="PlayQuiz" asp-route-id="@quizBasic.Id">Play</a> </span>
                <span>@quizBasic.QuizName</span>
                @{
                    if (ViewBag.UserId == quizBasic.ApplicationUserId)
                    {
                        <a asp-controller="Quiz" asp-action="DeleteQuiz" asp-route-id="@quizBasic.Id" name="btnDelete" class="float-right btn btn-danger">Delete</a>
                        <a asp-controller="Quiz" asp-action="EditQuiz" asp-route-id="@quizBasic.Id" name="btnEdit" class="float-right btn btn-info">Edit</a>
                    }
                }
            </li>
        }
    </ul>
</div>

<script>

</script>

B03.EE.BlanckeK.Web/Views/Quiz/PlayQuiz.cshtml
@using B03.EE.BlanckeK.Lib.Models
@{
    int questionCounter = 0;
    string questionString = "input" + questionCounter;
}

@model Quiz

<article class="card">
    <div class="card-header text-center">You are playing '@Model.QuizName'</div>
    <br />
    <div class="card-body" style="margin-bottom: 0%">
        <div class="card">
            @foreach (var question in Model.Questions)
            {
                <div id="login_for_review" class="modal hide" role="dialog">

                </div>
                <div class="card">
                    <fieldset id="@questionCounter" name="question">
                        <legend class="card-header" style="background-color: lightblue; color: black; margin-bottom: 1%">@question.QuestionText<span id="@questionCounter span" class="float-right"></span></legend>
                        @foreach (var answer in question.AnswerList)
                        {
                            <label class="input-group" style="margin-left: 2%">
                                <input style="margin-right: 1%" type="checkbox" name="@questionString" value="@answer.IsCorrectAnswer">@answer.AnswerText
                            </label>
                        }
                    </fieldset>
                </div>
                questionCounter++;
                questionString = "input" + questionCounter;
            }
            <button class="btn-success" type="button" onclick="validateQuiz()" id="answer" value="submit">Submit</button>
        </div>
    </div>
    <div class="card-footer">
        <a asp-controller="Quiz" asp-action="Index" class="btn btn-primary">Back to list</a>

    </div>
</article>

<div id="myModal" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>
        <p id="scoreBoard"></p>
    </div>
</div>



<script src="~/js/ValidateQuiz.js"></script>